const CATEGORIES = [
  { key: 'skincare', query: 'skin care' },
  { key: 'makeup', query: 'makeup' },
  { key: 'clothes', query: 'clothes' },
  { key: 'mobile', query: 'mobile phone' },
  { key: 'powerbank', query: 'power bank' },
  { key: 'earbuds', query: 'earbuds' },
  // Brand-led queries: a bare "watch"/"shoes" search returns almost entirely
  // white-label listings, which the brand gate in config/brands.js then drops.
  { key: 'watch', query: 'titan casio fastrack watch' },
  { key: 'handbag', query: 'handbag' },
  { key: 'fans', query: 'fan' },
  { key: 'perfume', query: 'perfume' },
  { key: 'bulbs', query: 'led bulb' },
  { key: 'men-grooming', query: 'men grooming' },
  { key: 'women-grooming', query: 'women grooming' },
  { key: 'beds', query: 'bed' },
  { key: 'toys', query: 'toys' },
  { key: 'electronics-accessories', query: 'usb cable charger' },
  { key: 'sweets', query: 'sweets' },
  { key: 'gym', query: 'gym equipment' },
  { key: 'tools', query: 'tools' },
  { key: 'mouse-keyboard', query: 'mouse keyboard' },
  { key: 'helmet', query: 'helmet' },
  { key: 'purifier', query: 'air purifier' },
  { key: 'household', query: 'household items' },
  { key: 'shoes', query: 'nike adidas puma campus shoes' },
  { key: 'sandals', query: 'bata sparx paragon sandals' },
  { key: 'extension-board', query: 'extension board' },
  { key: 'birthday-party', query: 'birthday party supplies' },
  // DealsSpy-style staples: branded everyday consumables that dominate their feed
  { key: 'shampoo', query: 'shampoo' },
  { key: 'soap-bodywash', query: 'soap body wash' },
  { key: 'face-wash', query: 'face wash' },
  { key: 'oral-care', query: 'toothpaste oral care' },
  { key: 'detergent', query: 'detergent cleaning' },
  { key: 'kitchen-appliances', query: 'kitchen appliances' },
  { key: 'lunch-box', query: 'lunch box' },
  { key: 'luggage', query: 'trolley bag luggage' },
  { key: 'snacks', query: 'snacks' },
  // High-frequency items in DealsSpy's feed (studied across 10 pages)
  { key: 'speakers', query: 'bluetooth speaker soundbar' },
  { key: 'smartwatch', query: 'smartwatch' },
  { key: 'gaming', query: 'gaming accessories' },
  { key: 'sports', query: 'badminton cricket sports equipment' },
  { key: 'car-accessories', query: 'car accessories' },
  { key: 'cookware', query: 'cookware dinner set' },
  { key: 'tv', query: 'smart tv' },
  { key: 'laptop', query: 'laptop' },
  // Long-tail categories recurring across DealsSpy pages 11-30
  { key: 'baby-care', query: 'baby care products' },
  { key: 'pet-supplies', query: 'pet supplies' },
  { key: 'stationery', query: 'stationery office supplies' },
  { key: 'garden', query: 'gardening supplies' },
  { key: 'health-wellness', query: 'health wellness supports' },
  { key: 'storage-containers', query: 'storage containers organizer' },
  { key: 'home-decor', query: 'home decor' },
  { key: 'hair-oil', query: 'hair oil' },
  { key: 'innerwear', query: 'innerwear' },
  { key: 'monitor', query: 'computer monitor' },
  { key: 'camera', query: 'camera' },
];

module.exports = { CATEGORIES };
