const CATEGORIES = [
  { key: 'skincare', query: 'cerave minimalist plum dot key skincare' },
  { key: 'makeup', query: 'lakme maybelline swiss beauty sugar makeup' },
  { key: 'clothes', query: 'levis us polo jack jones hrx roadster men clothes' },
  { key: 'powerbank', query: 'mi ambrane anker boat power bank' },
  { key: 'earbuds', query: 'boat noise realme oneplus earbuds' },
  // Brand-led queries: a bare "watch"/"shoes" search returns almost entirely
  // white-label listings, which the brand gate in config/brands.js then drops.
  { key: 'watch', query: 'titan casio fastrack watch' },
  { key: 'handbag', query: 'lavie zouk caprese baggit handbag' },
  { key: 'fans', query: 'crompton havells orient atomberg fan' },
  { key: 'perfume', query: 'wild stone bella vita park avenue perfume' },
  { key: 'bulbs', query: 'led bulb' },
  { key: 'men-grooming', query: 'philips beardo gillette men grooming' },
  { key: 'women-grooming', query: 'philips veet bombae women grooming' },
  { key: 'beds', query: 'bed' },
  { key: 'toys', query: 'toys' },
  { key: 'electronics-accessories', query: 'anker boat spigen c type cable fast charger' },
  { key: 'sweets', query: 'haldirams bikaji cadbury ferrero rocher sweets' },
  { key: 'gym', query: 'boldfit gym equipment dumbell yoga mat' },
  { key: 'mouse-keyboard', query: 'logitech dell hp wireless keyboard mouse combo' },
  { key: 'helmet', query: 'helmet' },
  { key: 'purifier', query: 'air purifier' },
  { key: 'household', query: 'household items' },
  { key: 'shoes', query: 'nike adidas puma reebok red tape campus shoes' },
  { key: 'sandals', query: 'bata sparx shoetopia catwalk women sandals flats heels' },
  { key: 'women-clothing', query: 'libas rangriti tokyo talkies sassafras women kurti dress' },
  { key: 'extension-board', query: 'extension board' },
  { key: 'birthday-party', query: 'birthday party supplies' },
  // DealsSpy-style staples: branded everyday consumables that dominate their feed
  { key: 'shampoo', query: 'shampoo' },
  { key: 'soap-bodywash', query: 'soap body wash' },
  { key: 'face-wash', query: 'face wash' },
  { key: 'oral-care', query: 'colgate sensodyne oral b toothpaste' },
  { key: 'detergent', query: 'detergent cleaning' },
  { key: 'kitchen-appliances', query: 'kitchen appliances' },
  { key: 'lunch-box', query: 'lunch box' },
  { key: 'luggage', query: 'american tourister safari skybags trolley bag' },
  { key: 'snacks', query: 'happilo nutraj farmley dry fruits snacks' },
  // High-frequency items in DealsSpy's feed (studied across 10 pages)
  { key: 'speakers', query: 'jbl partybox boat sony zebronics party speaker soundbar' },
  { key: 'smartwatch', query: 'noise boat fire boltt smartwatch' },
  { key: 'gaming', query: 'razer logitech cosmic byte redragon gaming controller' },
  { key: 'sports', query: 'badminton cricket sports equipment' },
  { key: 'car-accessories', query: 'car accessories' },
  { key: 'cookware', query: 'cookware dinner set' },
  { key: 'tv', query: 'smart tv' },
  { key: 'laptop', query: 'laptop' },
  // Long-tail categories recurring across DealsSpy pages 11-30
  { key: 'baby-care', query: 'pampers huggies sebamed luvlap baby care' },
  { key: 'pet-supplies', query: 'pet supplies' },
  { key: 'stationery', query: 'stationery office supplies' },
  { key: 'garden', query: 'gardening tools plant pots seeds' },
  { key: 'health-wellness', query: 'muscleblaze optimum nutrition whey protein' },
  { key: 'storage-containers', query: 'storage containers organizer' },
  { key: 'home-decor', query: 'home decor' },
  { key: 'hair-oil', query: 'hair oil' },
  { key: 'innerwear', query: 'jockey amul macho van heusen men innerwear vest trunks' },
  { key: 'monitor', query: 'computer monitor' },
  { key: 'camera', query: 'camera' },
];

module.exports = { CATEGORIES };
